### ISSUE TITLE
Feature suggestion: SVG support

### ISSUE THREAD

**Issue by brandonmcconnell** [marella/material-symbols#1]
Congrats on the new project! I would love if you could add SVG icon support to your to-do list for this project, similar to [material-icons](https://github.com/material-icons/material-icons).

Cheers!

**Comment by marella** [comment]
Thanks. I will add SVGs soon.

**Comment by marella** [comment]
I added SVGs with different weights to separate packages ([`@material-symbols/svg-400`](https://www.npmjs.com/package/@material-symbols/svg-400) for weight 400 etc.) due to package file limit. Since Material Symbols have lot of variations (fill, weight, grade, optical size), I included only some of them (fill, weight) to keep the package size small.
Please see [README](https://github.com/marella/material-symbols/tree/main/svg/400#readme) for more info.
